### ISSUE TITLE
شروع

### ISSUE THREAD

**Issue by EngMohadese** [EngMohadese/AndroidProject#1]
از این قسمت میتونیم با هم به نوعی چت کنیم  و مشکلات رو در میون بگذاریم :) 
@mrz8

**Comment by noushinriahi** [comment]
سلام. مشخص شد هر کدام چه بخشی از کد را به عهده می گیرید؟

**Comment by mrz8** [comment]
سلام استاد
بله مشخص شده
محدثه  کد قسمت بازی را می زنه
من بقیه کد های مربوط به بازی شامل صفحه شروع و صفحه نقشه بازی و صفحه تنظیمات و صفحه ی اموزش قبل از شروع بازی + گرافیک کار (دگمه ها و تصاویر پس زمینه ) رو انجام می دهم

**Comment by EngMohadese** [comment]
به نظرم برای نظم گرفتن کارا ، یه سری قاونو بذاریم ، مثل تایم پوش کردن ، پیشنهاد من پوش کردن به صورت هر دو روز یک باره تا تفاوت کارها خیلی زیاد نشه ، و کنارش باید اسمامی مشخص و درستی برای فایل هامون در نظر بگیریم که وقتی پوش میکنیم فایل هایی که محتوای متفاوتی دارن رو یکی تشخیص نده ،  فک کنم من اول هر چیزی که ایجاد میکنم یه محدثه بذارمم درست میشه
