### ISSUE TITLE
سوال

### ISSUE THREAD

**Issue by EngMohadese** [EngMohadese/AndroidProject#4]
من توی کد به یه مشکلی برخوردم که هنوز نفهمیدم چرا ایجاد میشه ، به نظرم ساختار کدم برای پردازش توی اندروید یه کم پیچیده شده البته حدس میزنم، حالا یه مساله دیگه نحوه پخش صوته ، به نظر شما اگر صدا های از قبل ایجاد شده رو برای هر تصویر پخش کنیم اشکالی نداره؟ به این خاطر که من هنوز نتونستم راهی برای ایجاد صوت با توجه به فرکانس و کارهایی که توی متلب انجام دادن بچه ها پیدا کنم !
@noushinriahi

**Comment by noushinriahi** [comment]
من متن? در?افت ن?ردم.

________________________________
